services:
    api: 
        build: .
        container_name: konveksi
        restart: unless-stopped
        environment:
            APP_ENV: production
            APP_DEBUG: false
            DB_CONNECTION: mysql
            DB_HOST: db
            DB_PORT: 3306
            DB_DATABASE: laravel
            DB_USERNAME: root
            DB_PASSWORD: secret
            APP_KEY: base64:1VsNoW9NCZIxHTR2phhDknnh/icwGqP+JMZYY2Khjak=
            MISTRAL_API_TOKEN: Ae1bLsGBfyb6IPjuQoQGEnkqnci4pNjq
            MISTRAL_MODEL: mistral-small-latest
            MAIL_MAILER: smtp
            MAIL_HOST: smtp.gmail.com
            MAIL_PORT: 587
            MAIL_USERNAME: cukbujang@gmail.com
            MAIL_PASSWORD: "qpyi wklk azzo dswt"
            MAIL_FROM_ADDRESS: "no-reply@gmail.com"
            MAIL_FROM_NAME: "${APP_NAME}"
            MAIL_ENCRYPTION: tls
        ports:
            - "6310:8080"
        volumes:
            - konveksi_storage:/var/www/html/storage
        depends_on:
            - db
        networks:
            - konveksi_network

    db:
        image: mysql:8.0
        container_name: mysql_db
        restart: unless-stopped
        environment:
            MYSQL_ROOT_PASSWORD: secret
            MYSQL_DATABASE: laravel
            MYSQL_USER: laraveluser
            MYSQL_PASSWORD: laravelpass
        volumes:
            - mysql_data:/var/lib/mysql
        networks:
            - konveksi_network

    phpmyadmin:
        image: phpmyadmin/phpmyadmin
        container_name: phpmyadmin
        restart: unless-stopped
        environment:
            PMA_HOST: db
            MYSQL_ROOT_PASSWORD: secret
        ports:
            - "1289:80"
        depends_on:
            - db
        networks:
            - konveksi_network

networks:
    suka_bersih_network:
        driver: bridge

volumes:
    mysql_data:
    suka_bersih_storage: